--Sentry Role / Privilege extract
SELECT
SENTRY_ROLE.ROLE_ID,
SENTRY_ROLE.ROLE_NAME,
SENTRY_DB_PRIVILEGE.DB_PRIVILEGE_ID,
SENTRY_DB_PRIVILEGE.PRIVILEGE_SCOPE,
SENTRY_DB_PRIVILEGE.SERVER_NAME,
SENTRY_DB_PRIVILEGE.DB_NAME,
SENTRY_DB_PRIVILEGE.TABLE_NAME,
SENTRY_DB_PRIVILEGE.COLUMN_NAME,
SENTRY_DB_PRIVILEGE.URI,
SENTRY_DB_PRIVILEGE.ACTION,
SENTRY_DB_PRIVILEGE.WITH_GRANT_OPTION
FROM SENTRY_ROLE_DB_PRIVILEGE_MAP
JOIN SENTRY_ROLE ON SENTRY_ROLE.ROLE_ID=SENTRY_ROLE_DB_PRIVILEGE_MAP.ROLE_ID
JOIN SENTRY_DB_PRIVILEGE ON SENTRY_DB_PRIVILEGE.DB_PRIVILEGE_ID=SENTRY_ROLE_DB_PRIVILEGE_MAP.DB_PRIVILEGE_ID;

--Sentry Role / Group extract
SELECT SENTRY_ROLE.ROLE_ID,SENTRY_ROLE.ROLE_NAME,SENTRY_GROUP.GROUP_NAME
FROM SENTRY_ROLE_GROUP_MAP
JOIN SENTRY_ROLE ON SENTRY_ROLE.ROLE_ID=SENTRY_ROLE_GROUP_MAP.ROLE_ID
JOIN SENTRY_GROUP ON SENTRY_GROUP.GROUP_ID=SENTRY_ROLE_GROUP_MAP.GROUP_ID;
